### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by neuromancer** [OpenAWE-Project/OpenAWE#2]
I think people will be more interested in testing this neat re-implementation and maybe collaborate with some code if you show the current state of this port in the README. Even early screenshots are fine!

**Comment by Nostritius** [comment]
Thanks for your suggestion, I have added a screenshot of american nightmare in the current version. I first thought to add also a screenshot for Alan Wake, but I will delay this until openawe can separate between Alan Wake and American Nightmare.
