### ISSUE TITLE
emmintrin.h

### ISSUE THREAD

**Issue by Mzed3D** [OpenAWE-Project/OpenAWE#31]
Hi! When compiling OpenAWE on an Arm64 board (Odroid N2+ in my case) I get the error:

fatal error: emmintrin.h: No such file or directory

And after a while the compilation fails.
Deleting "include <emmintrin.h>" from /src/codecs/yuv2rgb.cpp solves the problem.

**Comment by Nostritius** [comment]
I see the problem, emmintirin.h gives the intrinsics for SSE2, a processor extension for vector calculation. It needs to be encapsulated into certain preprocessor definitions as it is done with the body of convertYUV2RGB_SSE2. I will create a small fix for that.

**Comment by Nostritius** [comment]
Could you test if that works for you?

**Comment by Mzed3D** [comment]
Now it works!
