### ISSUE TITLE
Incorrect boundaries of instanced foliage

### ISSUE THREAD

**Issue by maaxxaam** [OpenAWE-Project/OpenAWE#38]
Ever since foliage started using instanced rendering in commit d7306490c0b7047ede1e2b9c2be5897b1db15ec1, it gets culled away too agressively, causing trees and bushes to pop in and out of frame. It could be happenning because an instanced object does not aggregate foliage boundaries but uses properties of a random foliage instead.

**Comment by Nostritius** [comment]
I will take a look on that

**Comment by Nostritius** [comment]
I have changed the way, the bounding spheres are combined, and it should now work again. Could you test this?

**Comment by maaxxaam** [comment]
Thank you for the quick reply! Commit bc622b9f50be61133260846e48a04ca5e519741b seems to resolve the issue - foliage looks fine now.
